# ----------------------- #
#           Site          #
# ----------------------- #
# Site-level configuration. Plugin which require extra
# data should have that in plugin-specific configuration
# All plugins should be able to depend upon these settings

title:              Jekyll Blog
author:             John Smith
email:              mail@example.dev
theme:              classic
location:           'New York, New York'

# ----------------------- #
#         Layouts         #
# ----------------------- #
# Anything specific to your layout can go here

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #
delicious_user:
delicious_count:    3
delicious_show:     true

disqus_shortname:

facebook_user:
facebook_show:      true

flickr_user:
flickr_show:        true

feedburner_name:

ga_tracking_id:

github_user:
github_repo:
github_forkme:      false
github_show:        true

googleplus_user:
googleplus_show:    true

pinboard_user:
pinboard_count:     3
pinboard_show:      true

twitter_user:
twitter_show:       true

# ----------------------- #
#          Jekyll         #
# ----------------------- #
# All of these settings are required

# Set this to true to disable plugins
safe:               false
# Enables or disables Jekyll from recreating the site when files are modified.
regeneration:       true
# Fires up a server that will host your _site directory
server:             false
# Changes the port that the Jekyll server will run on
server_port:        4000
# Serve website from a given base URL
baseurl:            /
# Sets site.url, useful for environment switching
url:                http://example.dev

# Changes the directory where Jekyll will look to transform files
source:             ./source
# Changes the directory where Jekyll will write files to
destination:        ./_site
# Changes the directory where Jekyll will look for plugins
plugins:            ./_plugins

# Inclusion/exclusion of future dated posts
future:             true
# Produces an index for related posts. Install rb-gsl and libgsl to speed this up
lsi:                true
# Built-in Code highlighting with Pygments. Disabled because we use a plugin for this
pygments:           false
# Uses [engine] instead of Maruku. Use redcarpet since it's the new hotness
markdown:           redcarpet
# Controls the URLs that posts are generated with.
permalink:          /:year/:month/:day/:title/
# A list of directories and files to exclude from the conversion
exclude:            README.textile Rakefile Gemfile Gemfile.lock requirements.txt

# ----------------------- #
#         Rakefile        #
# ----------------------- #
# This section holds Rakefile-specific configuration
# Contents subject to change

# SSH Connection info
ssh_user:           deploy@example.dev
# Port to connect with
ssh_port:           22
# Deploy path to sync _site directory to
deploy_path:        /var/www/example.dev/
# Port to serve
serve_port:         4000
# Default editor to use when creating new posts
editor:             subl
# Enable sharing
sharing:            true
# Enable comments
comments:           true
# Default category for new posts
category:           Code
# Default format for new posts
format:             markdown
# Sets a testing url
test_url:           http://example.dev

# ----------------------- #
#         Plugins         #
# ----------------------- #
generators:
  generic_index:
    category:
    tag:
      related:      true

tags:
  backtick:         rainbow

highlighter:        coderay
